name: Publish package

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "*"

jobs:
  luarocks-upload:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Lux
        uses: lumen-oss/gh-actions-lux@d12a6bdf3a380de5b9d142272e6fd95d28b44b8d # v1

      - name: Upload
        env:
          LUX_API_KEY: ${{ secrets.LUX_API_KEY }}
        run: lx upload
