name: Publish

on:
  workflow_dispatch:
    inputs:
      skip_luarocks:
        description: 'Skip luarocks upload'
        required: true
        default: true
        type: boolean
  release:
    types: [published]

jobs:
  build:
    name: ${{ matrix.job.target }}-${{ matrix.lua_version }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-24.04, target: x86_64-linux }
          - { os: ubuntu-24.04-arm, target: aarch64-linux }
          - { os: macos-14, target: aarch64-darwin }
          - { os: windows-2025, target: x86_63-windows-msvc }
        lua_version:
          - lua51
          - lua52
          - lua53
          - lua54
          - lua55

    env:
      CARGO_INCREMENTAL: 0
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_NET_RETRY: 10
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      RUSTFLAGS: -D warnings
      RUSTUP_MAX_RETRIES: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
        if: endsWith(matrix.job.target, '-msvc')

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1

      - name: Build
        run: |
          cargo build --release --no-default-features --features module,${{ matrix.lua_version }}

      - name: Rename for Lua
        if: endsWith(matrix.job.target, '-darwin')
        run: |
          cp target/release/libminijinja_lua.dylib minijinja.so

      - name: Rename for Lua
        if: endsWith(matrix.job.target, '-linux')
        run: |
          cp target/release/libminijinja_lua.so minijinja.so

      - name: Rename for Lua
        if: endsWith(matrix.job.target, '-msvc')
        run: |
          cp target/release/minijinja.dll minijinja.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.job.target }}-${{ matrix.lua_version }}
          path: "minijinja.so"
          if-no-files-found: "error"

  luarocks-upload:
    if: ${{ !inputs.skip_luarocks }}
    runs-on: ubuntu-24.04

    env:
      LUA_VERSION: 5.4
      LUX_VERSION: 0.28.0

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Lux
        uses: lumen-oss/gh-actions-lux@d12a6bdf3a380de5b9d142272e6fd95d28b44b8d # v1
        with:
          version: ${{ env.LUX_VERSION }}

      - name: Upload
        env:
          LUX_API_KEY: ${{ secrets.LUX_API_KEY }}
        run: lx --lua-version ${{ env.LUA_VERSION }} upload
